services:
  - type: web
    name: coa-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: GROQ_API_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true 